if(typeof Asey=="undefined")window.Asey={};Asey.Assert={};Asey.Assert.fail=function(a){alert("AseyJSAssert: "+a)};Asey.Assert.assert=function(a,b){if(!a)throw Error(b);};$.extend($.browser,{SafariMobile:navigator.userAgent.toLowerCase().match(/iP(hone|ad|od)/i)});if(!Array.indexOf)Array.prototype.indexOf=function(a){for(var b=0;b<this.length;++b)if(this[b]==a)return b;return-1};Asey.Plugins={};Asey.Utils={};
Asey.Utils.getCssVendorPrefix=function(){if(!Asey.Utils.isDefined(Asey.Utils.getCssVendorPrefix.flag))Asey.Utils.getCssVendorPrefix.flag=/webkit/i.test(navigator.appVersion)?"-webkit":/firefox/i.test(navigator.userAgent)?"-moz":/trident/i.test(navigator.userAgent)?"-ms":"opera"in window?"-o":"";return Asey.Utils.getCssVendorPrefix.flag};Asey.Utils.wrapElement=function(a,b){a.parentNode.replaceChild(b,a);b.appendChild(a)};
Asey.Utils.firstChild=function(a,b){for(var c=0;c<a.childNodes.length;c++){var d=a.childNodes[c];if(d.nodeType==1&&(!b||b.matches(d)))return d}return null};Asey.Utils.firstDescendant=function(a,b,c){for(var d=0;d<a.childNodes.length;d++){var f=a.childNodes[d];if(f.nodeType==1){if(!b||b.matches(f))return f;if(!c||!c.matches(f))if(f=Asey.Utils.firstDescendant(f,b,c))return f}}return null};
Asey.Utils.descendants=function(a,b,c,d){if(!d)d=[],d.forEach=function(a){for(var b=0;b<this.length;b++)if(a(this[b]))break},d.forEachTry=function(a){for(var b=0;b<this.length;b++)try{if(a(this[b]))break}catch(c){}};for(var f=0;f<a.childNodes.length;f++){var g=a.childNodes[f];g.nodeType==1&&((!b||b.matches(g))&&d.push(g),(!c||!c.matches(g))&&Asey.Utils.descendants(g,b,c,d))}return d};Asey.Utils.children=function(a,b){return Asey.Utils.descendants(a,b,Asey.Utils.Match.always)};Asey.Utils.Match={};
Asey.Utils.Match.ByClass=function(a){this.cl=a};Asey.Utils.Match.ByClass.prototype.matches=function(a){return $(a).hasClass(this.cl)};Asey.Utils.Match.ByNodeName=function(a){this.nm=a.toLowerCase()};Asey.Utils.Match.ByNodeName.prototype.matches=function(a){return this.nm==a.nodeName.toLowerCase()};Asey.Utils.Match.ByFixed=function(a){this.matchResult=a};Asey.Utils.Match.ByFixed.prototype.matches=function(){return this.matchResult};Asey.Utils.Match.byClass=function(a){return new Asey.Utils.Match.ByClass(a)};
Asey.Utils.Match.byNodeName=function(a){return new Asey.Utils.Match.ByNodeName(a)};Asey.Utils.Match.byFixed=function(a){return new Asey.Utils.Match.ByFixed(a)};Asey.Utils.Match.always=Asey.Utils.Match.byFixed(!0);Asey.Utils.Match.never=Asey.Utils.Match.byFixed(!1);Asey.Utils.moveChildren=function(a,b){for(;a.childNodes.length>0;)b.appendChild(a.childNodes[0])};Asey.Utils.copyChildren=function(a,b){for(var c=0;c<a.childNodes.length;c++)b.appendChild(a.childNodes[c].cloneNode(!0))};
Asey.Utils.copyChildrenBefore=function(a,b){for(var c=0;c<a.childNodes.length;c++)b.parentNode.insertBefore(a.childNodes[c].cloneNode(!0),b)};Asey.Utils.pixelRound=function(a){return Math.floor((a*100+0.5)/100)};Asey.Utils.getCurrentHTMLFileName=function(a){var b=document.location.href;b.charAt(b.length-1)=="/"?b="index":(b=b.substring(b.lastIndexOf("/")+1),b=b.indexOf("#")==0?"index":b.substring(0,b.lastIndexOf(".")));a&&(b+=".html");return b};
Asey.Utils.getPageStyleSheet=function(){for(var a=0;a<document.styleSheets.length;++a){var b=document.styleSheets[a],c=b.ownerNode?b.ownerNode:b.owningElement;if(c&&c.id=="pagesheet")return b}};Asey.Utils.getStyleSheetRuleById=function(a,b){var c="#"+b.toLowerCase();return Asey.Utils.anyStyleSheetRule(a,function(a){return a.toLowerCase()==c})};
Asey.Utils.anyStyleSheetRule=function(a,b){var c=!1,d;try{d=a.cssRules}catch(f){}if(!d)c=!0,d=a.rules;if(!d)return null;for(var g=0;g<d.length;++g){var k=d[g];if(Asey.Utils.isDefined(k.selectorText))if(c){if(b(k.selectorText))return k}else for(var h=k.selectorText.split(/\s*,\s*/),j=0;j<h.length;j++)if(b(h[j]))return k}return null};Asey.Utils.getRuleProperty=function(a,b){return a.style.getPropertyValue?a.style.getPropertyValue(b):a.style.getAttribute(b)};
Asey.Utils.setRuleProperty=function(a,b,c){a.style.setProperty?a.style.setProperty(b,c,""):a.style.setAttribute(b,c,0)};Asey.Utils.removeRuleProperty=function(a,b){a.style.removeProperty?a.style.removeProperty(b):a.style.removeAttribute(b,0)};
Asey.Utils.cloneStyleSheetRule=function(a){if(!Asey.Utils.isDefined(Asey.Utils.cloneStyleSheetRule.newNumber))Asey.Utils.cloneStyleSheetRule.newNumber=1;var b=Asey.Utils.getPageStyleSheet(a),c=Asey.Utils.getStyleSheetRuleById(b,a),d="c"+Asey.Utils.cloneStyleSheetRule.newNumber++,f="#"+d;b.insertRule?b.insertRule(c.cssText.replace("#"+a,f),b.cssRules.length):b.addRule(f,c.style.cssText);return d};
Asey.Utils.toCamelCase=function(a){for(var b=Asey.Utils.toCamelCase.exp;b.test(a);a=a.replace(b,RegExp.$1.toUpperCase()));return a};Asey.Utils.toCamelCase.exp=/-([a-z])/;Asey.Utils.getStyleValue=function(a,b){var c=a.style[Asey.Utils.toCamelCase(b)];c||(document.defaultView?c=document.defaultView.getComputedStyle(a,"").getPropertyValue(b):a.currentStyle&&(c=a.currentStyle[Asey.Utils.toCamelCase(b)]));c&&c.match(/(\d+)px/)&&(c=parseInt(c.substring(0,c.length-2)));return c};
Asey.Utils.getCanvasDirection=function(a,b){var c=a.closest("*[data-rotate]"),c=c.length>0?parseFloat(c.data("rotate"))%360:0;return{dir:c>=0&&c<=45||c>=135&&c<=225||c>=315&&c<360?b:b==="horizontal"?"vertical":"horizontal",reverse:b==="horizontal"?c>=135&&c<=315:c>=45&&c<=225}};Asey.Utils.urlParam=function(a,b){var c=RegExp("[\\?&]"+b+"=([^&#]*)").exec(a);return c?c[1]:null};
Asey.Utils.processHyperlink=function(a){var b=a.href,c=$(window),a=$(a),d=a.attr("target");if(!d||d=="_self"){var f=b.lastIndexOf("/"),d=b.lastIndexOf("#"),g=a.attr("class").match(/anim_(\w+)/);if(g&&d>f){var a=c.data("scrollWrapper"),k=b.substring(d),d=Asey.Utils.getAnchorWithDestination(k).offset(),b=g[1],h=a||window,f=document.documentElement||document.body,g=(a?a.scrollHeight():f.scrollHeight)-c.height(),c=(a?a.scrollWidth():f.scrollWidth)-c.width(),j=Math.min(g,d.top+(a&&!a.isStandard()?a.scrollTop():
0)),i=Math.min(c,d.left+(a&&!a.isStandard()?a.scrollLeft():0)),c=function(){h.scrollTo(i,j);try{history.replaceState({})}catch(a){if(!jQuery.browser.msie||jQuery.browser.version>7)window.location.hash=k}};try{history.pushState({},null,k)}catch(l){}if(window.scrollTo||void 0!==a){var a=a||$(document),m=a.scrollLeft(),o=a.scrollTop(),q=m,p=o;$({scrollDistance:0}).animate({scrollDistance:1},{duration:1E3,easing:b,step:function(a){a!=0&&(p=a*(j-o),q=a*(i-m),h.scrollTo(m+q,o+p))},complete:c})}else $("html,body").animate({scrollTop:j,
scrollLeft:i},1E3,b,c);return!1}}(c=Asey.Utils.urlParam(b,"devicelock"))&&Asey.Utils.createCookie("devicelock",c,0);return!0};var actionStack=[];Asey.Utils.redirectCancelled=!1;Asey.Utils.redirectHyperlink=function(a){if(Asey.Utils.redirectCancelled)setTimeout(function(){Asey.Utils.redirectCancelled=!1},0);else if(actionStack=[],Asey.Utils.processHyperlink(a)&&!Asey.Utils.isIBE()){var b=$(a).attr("target");b||(b="_self");window.open(a.href,b)}};
Asey.Utils.redirectHyperlinkInNewTab=function(a,b){if(Asey.Utils.redirectCancelled)setTimeout(function(){Asey.Utils.redirectCancelled=!1},0);else{actionStack=[];thisWindow=window.self;var c=window.open(a);b?c.focus():thisWindow.focus()}};Asey.Utils.isMouseLeftClick=function(a){return a.which==1};Asey.Utils.isMouseMiddleClick=function(a){return a.which==2};Asey.Utils.isRedirectLinkKeyboardAction=function(a){return a.which==13};
Asey.Utils.addHyperlinkAnchor=function(a){a=$(a);a.bind("mousedown",function(a){(Asey.Utils.isMouseLeftClick(a)||Asey.Utils.isMouseMiddleClick(a))&&actionStack.push(this)});a.bind("mouseup keyup",function(a){if(Asey.Utils.isMouseLeftClick(a)&&actionStack.indexOf(this)!=-1)a.ctrlKey||a.metaKey?Asey.Utils.redirectHyperlinkInNewTab(this.href,a.shiftKey):Asey.Utils.redirectHyperlink(this);else if(Asey.Utils.isMouseMiddleClick(a)&&actionStack.indexOf(this)!=-1)if(jQuery.browser.webkit||!a.target.href&&
jQuery.browser.msie)Asey.Utils.redirectHyperlinkInNewTab(this.href,a.shiftKey);else return actionStack=[],!0;else Asey.Utils.isRedirectLinkKeyboardAction(a)&&Asey.Utils.redirectHyperlink(this);return!1});Asey.Utils.isIBE()||a.bind("click",function(){return!1})};
Asey.Utils.addHyperlinkBlock=function(a){var b=$(a.parentNode);b.bind("mousedown",function(a){(Asey.Utils.isMouseLeftClick(a)||Asey.Utils.isMouseMiddleClick(a))&&actionStack.push(this);return!1});b.bind("mouseup keyup",function(b){Asey.Utils.isMouseLeftClick(b)&&actionStack.indexOf(this)!=-1?b.ctrlKey||b.metaKey?Asey.Utils.redirectHyperlinkInNewTab(a.href,b.shiftKey):Asey.Utils.redirectHyperlink(a):Asey.Utils.isMouseMiddleClick(b)&&actionStack.indexOf(this)!=-1?Asey.Utils.redirectHyperlinkInNewTab(a.href,
b.shiftKey):Asey.Utils.isRedirectLinkKeyboardAction(b)&&Asey.Utils.redirectHyperlink(a);return!1});Asey.Utils.isIBE()||b.bind("click",function(){return!1})};
Asey.Utils.prepHyperlinks=function(a){$("a.block").each(function(){var a=$(this.parentNode);Asey.Utils.addHyperlinkBlock(this);a.find("a.nonblock").each(function(){var a=$(this);if(a.data("registeredNonBlockLink")===!0)return!1;Asey.Utils.addHyperlinkAnchor(this);a.data("registeredNonBlockLink",!0)})});$("a.nonblock").each(function(){var a=$(this);a.data("registeredNonBlockLink")!==!0&&(a.parent('[class~="sbg"]').length>0?Asey.Utils.addHyperlinkAnchor(this):(a.attr("class").match(/anim_(\w+)/)||this.href.indexOf("devicelock=")!=
-1)&&$(this).bind("click",function(){return Asey.Utils.processHyperlink(this)}))});a&&Asey.Utils.enableAnchorLinksActiveState()};Asey.Utils.pathOnly=function(a){if(!a)return a;return a.replace(/#(?:[^#]+)$/,"").replace(/\?(?:[^\?]+)$/,"")};
Asey.Utils.enableAnchorLinksActiveState=function(){var a=$("#page"),b=a.outerWidth()/a.outerHeight()>2,c=[],a=$(window),d=Asey.Utils.getPageStyleSheet(),f=function(a){var b=a.parent('[class~="sbg"]');if(a.hasClass("MenuItem")||b.hasClass("MenuItem"))return"AseyMenuActive";if(a.hasClass("Button")||b.hasClass("Button"))return"ButtonSelected";return"AseyLinkActive"},g=function(){c.splice(0,c.length);$("a.nonblock,a.block").each(function(){Asey.Utils.saveHyperlinkInfo($(this),f($(this)),d,b,c)});c.sort(function(a,
b){if(a.from<b.from)return-1;if(a.from>b.from)return 1;return 0})};g();if(0!=c.length){var k=!1,h=a.data("scrollWrapper"),j=h||a,i=function(){k=!1;var a=b?j.scrollLeft():j.scrollTop(),d;a:{var i=0;d=c.length;for(var l;i<d;i++)if(l=c[i],l.from<=a&&a<=l.to){d=i;break a}d=-1}var n,s,i=Math.max(0,d);for(d=Math.min(d+2,c.length);i<d;i++)if(n=c[i],l=n.$elem.offset().left+(h&&!h.isStandard()?h.scrollLeft():0),s=n.$elem.offset().top+(h&&!h.isStandard()?h.scrollTop():0),n.from!=(b?l:s)){g();break}i=0;for(d=
c.length;i<d;i++){n=c[i];l=n.from<=a&&a<=n.to;n=n.hyperLinks;s=void 0;for(var v=0;v<n.length;v++)s=f(n[v]),l&&!n[v].hasClass(s)?n[v].addClass(s):!l&&n[v].hasClass(s)&&n[v].removeClass(s)}},l=function(){k||(k=!0,Asey.Utils.requestAnimationFrame(i))};(h=a.data("scrollWrapper"))?h.registerUpdateCallback(l):a.scroll(l);i()}};Asey.Utils.getAnchorWithDestination=function(a){if(!a||!a.replace)return $(a);return $(a.replace(/([\.\:])/gi,"\\$1"))};
Asey.Utils.saveHyperlinkInfo=function(a,b,c,d,f){var g=a.attr("href"),k=Asey.Utils.pathOnly(g),h=-1,j=a.attr("target"),i=window.location.href.replace(/#.*$/i,"");if(g&&-1!=g.indexOf("#")&&!(j&&j!="_self")&&!(0<=k.indexOf("/"))&&(i.charAt(i.length-1)=="/"&&(i+="index.html"),-1!=i.indexOf("/"+k,i.length-k.length-1))){var k=$(window).data("scrollWrapper"),l=g.substring(g.lastIndexOf("#")),a=a.parent('[class~="sbg"]').length>0||a.hasClass("block")?a.parent():a,m="#"+a.attr("id"),b="."+b;if(null!==Asey.Utils.anyStyleSheetRule(c,
function(a){return 0<=a.indexOf(m+b)||0<=a.indexOf(b+m)})){j=0;for(i=f.length;j<i;j++)if(f[j].href==g){h=j;break}if(-1==h){c=Asey.Utils.getAnchorWithDestination(l);if(c.length===0)return;j=k&&!k.isStandard();d=Math.floor(d?c.offset().left+(j?k.scrollLeft():0):c.offset().top+(j?k.scrollTop():0));k=Number.MAX_VALUE;j=0;for(i=f.length;j<i;j++)if(f[j].href!=g&&f[j].from==d){h=j;break}if(-1==h){j=0;for(i=f.length;j<i;j++){h=f[j];if(h.from<d&&d<h.to){k=h.to;h.to=d-1;break}h.from<=k&&(k=h.from-1)}f.push({hyperLinks:[],
from:d,to:k,$elem:c,href:g});h=f.length-1}}f[h].hyperLinks.push(a)}}};Asey.Utils.isIBE=function(){return Asey.Utils.readCookie("inbrowserediting")=="true"};
Asey.Utils.getNaturalWidth=function(a){var b=-1;a.naturalWidth!=null?b=a.naturalWidth:a.runtimeStyle?(a.runtimeStyle.width="auto",a.runtimeStyle.height="auto",a.runtimeStyle.borderWidth="0",a.runtimeStyle.padding="0",b=a.offsetWidth,a.runtimeStyle.width="",a.runtimeStyle.height="",a.runtimeStyle.borderWidth="",a.runtimeStyle.padding=""):(a=a.cloneNode(!0),a.className="",a.style.width="auto !important",a.style.height="auto !important",a.style.borderWidth="0 !important",a.style.padding="0 !important",
b=a.width);return b};
Asey.Utils.getNaturalHeight=function(a){var b=-1;a.naturalHeight!=null?b=a.naturalHeight:a.runtimeStyle?(a.runtimeStyle.width="auto",a.runtimeStyle.height="auto",a.runtimeStyle.borderWidth="0",a.runtimeStyle.padding="0",b=a.offsetHeight,a.runtimeStyle.width="",a.runtimeStyle.height="",a.runtimeStyle.borderWidth="",a.runtimeStyle.padding=""):(a=a.cloneNode(!0),a.className="",a.style.width="auto !important",a.style.height="auto !important",a.style.borderWidth="0 !important",a.style.padding="0 !important",
b=a.height);return b};Asey.Utils.pieLoading=!1;Asey.Utils.pieFunctionQueue=[];
Asey.Utils.needPIE=function(a){if(Asey.Utils.havePIE)a();else if(Asey.Utils.pieFunctionQueue.push(a),!Asey.Utils.pieLoading)Asey.Utils.pieLoading=!0,a="scripts/pie.js",a[0]=="/"&&(a=location.pathname.indexOf(".html")!=-1?location.pathname.substring(0,location.pathname.lastIndexOf("/"))+a:location.pathname+a,a=a.replace(/\/+/g,"/")),$.ajax({url:a,dataType:"script",complete:function(){if(Asey.Utils.isDefined(window.PIE)){Asey.Utils.havePIE=!0;Asey.Utils.pieLoading=!1;for(var a=0;a<Asey.Utils.pieFunctionQueue.length;++a)Asey.Utils.pieFunctionQueue[a]()}}})};
Asey.Utils.transformMarkupToFixBrowserProblemsPreInit=function(){jQuery.browser.msie?(jQuery("html").addClass("ie"),jQuery.browser.version<8&&Asey.Utils.changeLItoDIVs(),jQuery.browser.version<=8&&Asey.Utils.monitorCheckboxes()):jQuery.browser.SafariMobile&&jQuery("body").css("-webkit-text-size-adjust","none")};Asey.Utils.monitorCheckboxes=function(){var a=function(a){"checked"==a.attr("checked")?a.removeClass("not_checked").addClass("checked"):a.removeClass("checked").addClass("not_checked")};$(".fld-checkbox input[type=checkbox]").each(function(){a($(this))}).click(function(){a($(this))})};
Asey.Utils.transformMarkupToFixBrowserProblems=function(){Asey.Utils.havePIE=!1;jQuery.browser.msie&&jQuery.browser.version<=9&&(jQuery.browser.version<=9&&(Asey.Utils.addGradientFill(),Asey.Utils.addShadows()),jQuery.browser.version<9&&(Asey.Utils.applyIEFilterToPNGImages(),Asey.Utils.addRoundedCorners(),Asey.Utils.addRGBA(),Asey.Utils.removeEdgeAnimationBorderForIE78()),jQuery.browser.version<8&&Asey.Utils.fixWidthsForClearingInIE7());(jQuery.browser.msie&&jQuery.browser.version<9||jQuery.browser.webkit)&&
Asey.Utils.insertEmptyDivAfterPinnedColumnElements();Asey.Utils.fixTransformRotations();Asey.Utils.fixImageFramesWithRoundedCorners();Asey.Utils.fixSVGImages()};Asey.Utils.fixSVGImages=function(){var a=document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image","1.1"),b=$("html");a?b.addClass("svg"):(b.removeClass("svg"),$("body img").each(function(){var a=$(this),b=a.data("mu-svgfallback");b&&a.attr("src",b)}))};
Asey.Utils.applyIEFilterToPNGImages=function(){jQuery.browser.msie&&jQuery.browser.version<9&&$("body *").not(".aseyBgSizePolyfill img,.f3s_top,.f3s_mid,.f3s_bot").each(function(){var a=$(this);if(!a.data("mu-ie-matrix")&&(a.css("background-image").match(/\b.png/i)||this.nodeName&&this.nodeName.toLowerCase()=="img"&&a.attr("src").match(/\b.png/i))){var b=a.css("filter");a.css("filter",b?b+" progid:DXImageTransform.Microsoft.gradient(startColorstr=#00FFFFFF,endColorstr=#00FFFFFF)":"progid:DXImageTransform.Microsoft.gradient(startColorstr=#00FFFFFF,endColorstr=#00FFFFFF)")}})};
Asey.Utils.insertEmptyDivAfterPinnedColumnElements=function(){$(".pinned-colelem").each(function(){$("<div class='colelem'/>").insertAfter($(this))})};Asey.Utils.fixPNGImages=function(){$("body *").each(function(){var a=this,b=$(a);(b.css("background-image").match(/\b.png/i)||a.nodeName&&a.nodeName.toLowerCase()=="img"&&b.attr("src").match(/\b.png/i))&&Asey.Utils.needPIE(function(){b.css("-pie-png-fix","true");PIE.attach(a)})})};
Asey.Utils.addGradientFill=function(){$(".gradient").each(function(){var a=this;Asey.Utils.needPIE(function(){PIE.attach(a)})})};Asey.Utils.addShadows=function(){$(".shadow").each(function(){var a=this,b=$(a);Asey.Utils.needPIE(function(){b.data("mu-ie-matrix")||PIE.attach(a)})})};
Asey.Utils.fixImageFramesWithRoundedCorners=function(){Asey.Browser.Features.checkCSSFeature("border-radius")&&Asey.Browser.Features.checkCSSFeature("-webkit-border-radius")&&$(".rounded-corners").each(function(){if($(this).hasClass("clip_frame")){var a=Asey.Utils.firstDescendant(this,Asey.Utils.Match.byNodeName("img"));a&&$(a).wrap('<div class="clip_frame"></div>')}})};
Asey.Utils.addRoundedCorners=function(){$(".rounded-corners").each(function(){var a=this;Asey.Utils.needPIE(function(){var b=$(a);if(!b.data("mu-ie-matrix")){var c=b.css("filter");if(!c||!(c.toLowerCase().indexOf("opacity")>0&&c.indexOf("=100")<0)){if(a.childNodes.length&&!Asey.Browser.Features.checkCSSFeature("border-radius")&&(c=Asey.Utils.firstChild(a))&&c.nodeName.toLowerCase()=="img"){var c=$(c),d=c.attr("src"),f=b.css("background-color")+" ",g=c.css("margin-left");if(g=="0px"||g=="auto")g=c.css("padding-left");
var k=c.css("margin-top");if(k=="0px"||k=="auto")k=c.css("padding-top");c.css("visibility","hidden");b.css("background",f+"url("+d+") no-repeat "+g+" "+k)}if(jQuery.browser.msie&&jQuery.browser.version<8&&(b.css("border-left-width")==0||b.css("border-left-style")=="none")&&(b.css("border-right-width")==0||b.css("border-right-style")=="none")&&(b.css("border-top-width")==0||b.css("border-top-style")=="none")&&(b.css("border-bottom-width")==0||b.css("border-bottom-style")=="none"))b.css({"border-right-width":"1px",
"border-right-style":"solid","border-right-color":b.css("background-color")}),b.width(b.width()-1);PIE.attach(a)}}})})};Asey.Utils.addRGBA=function(){$(".rgba-background").each(function(){var a=this;Asey.Utils.needPIE(function(){PIE.attach(a)})})};Asey.Utils.resizeHeight=function(){$(".browser_width").each(function(){var a=$(this),b=a;a.parent().hasClass("sbg")&&(b=a.parent());a=$(a.children()[0]);a.css("position")!="fixed"&&(b.height(a.outerHeight()),a.watch("height",function(){b.height($(this).outerHeight())}))})};
Asey.Utils.fixWidthsForClearingInIE7=function(){$(".colelem").each(function(){var a=$(this).offset().left-$(this).parent().offset().left;if($(this).width()<1||$(this).width()+a<1)$(this).css("width",(a<0?1-a:1)+"px")})};Asey.Utils.removeEdgeAnimationBorderForIE78=function(){$(".animationContainer").each(function(){$(this).parent().html(function(a,b){return b.replace(/><\/iframe>$/gi,' frameBorder="0"></iframe>')})})};
Asey.Utils.initializeAnimations=function(a){var b=function(b){if(!0===a){var d=b.contents();$("#report-abuse",d).remove();$("#report-abuse-spacer",d).remove()}b.removeClass("an_invi")};$(".animationContainer").each(function(){var a=$(this);Asey.Utils.isIBE()||this.contentDocument&&"complete"==this.contentDocument.readyState?b(a):a.load(function(){b(a)})})};
Asey.Utils.fixTransformRotations=function(){Asey.Browser.Features.checkCSSFeature("transform")||$("*[data-mu-ie-matrix]").each(function(){var a=$(this),b=a.parent(),c=Math.round(a.data("mu-ie-matrix-dx")),d=Math.round(a.data("mu-ie-matrix-dy")),f=b.innerHeight(),g=b.innerWidth();a.css({filter:function(b,c){if(c)return c+" "+a.data("mu-ie-matrix");return a.data("mu-ie-matrix")},"margin-bottom":"-="+d}).removeClass("shadow");b.css({"margin-bottom":"-="+(b.innerHeight()-f),"margin-right":"-="+(b.innerWidth()-
g)});a.hasClass("actAsDiv")?(a.wrap('<span class="actAsDiv rotateWrapper"></span>'),a.parent().css("float",a.css("float"))):a.hasClass("actAsInlineDiv")?a.wrap('<span class="actAsInlineDiv rotateWrapper"></span>'):a.wrap('<div class="rotateWrapper"></div>');a.parent().css({top:d,left:c,position:"relative","margin-bottom":d})})};Asey.Utils.fullPage=function(a){$(window).data("stickyFooter").init(a)};
Asey.Utils.endsWith=function(a,b){if(!a||!b)return!1;Asey.Assert.assert("string"==typeof a,'Invalid type for "str" argument - expected string.');Asey.Assert.assert("string"==typeof b,'Invalid type for "ending" argument - expected string.');return a.substring(a.length-b.length)==b};Asey.Utils.firstDefined=function(){for(var a=0;a<arguments.length;a++)if(Asey.Utils.isDefined(arguments[a]))return arguments[a]};Asey.Utils.isDefined=function(a){return"undefined"!=typeof a};
Asey.Utils.getCSSIntValue=function(a,b){return Asey.Utils.tryParse(a.css(b),parseInt,0)};Asey.Utils.tryParse=function(a,b,c){if(!Asey.Utils.isDefined(a))return c;a=b(a);return!isNaN(a)?a:c};Asey.Utils.changeLItoDIVs=function(){var a=function(){var a=$(this),c=$("<div/>");c.addClass(a.attr("class"));c.attr("id",a.attr("id"));c.append(a.contents());a.replaceWith(c)};$("ul").each(function(){$(this).find("li").each(a)});$("ul").each(a)};Asey.Utils.initWidget=function(a,b){$(a).each(function(){b(this)})};
Asey.Utils.showWidgetsWhenReady=function(){jQuery(".disn").removeClass("disn");jQuery(".invi").removeClass("invi");jQuery(".widget_invisible").removeClass("widget_invisible")};
Asey.Utils.detachIframesAndObjectsToPauseMedia=function(a){var b=[];$("iframe, object",a).each(function(){var a=$(this);if(!(a.is("iframe")&&a.prop("src")=="")&&(!a.is("object")||!(jQuery.browser.msie&&jQuery.browser.version<9))){var d={};d.$next=a.next();d.$parent=a.parent();jQuery.browser.msie?(d.html=a.wrap("<div id='deleteMeWrapper'/>").parent().html(),a.remove(),d.$parent.children("div #deleteMeWrapper").remove()):(d.$node=a.clone(),a.remove());b.push(d)}});b.length&&a.data("detached",b);$("video",
a).each(function(){if(jQuery.browser.msie&&jQuery.browser.version==9&&this.pause&&this.getAttribute("autoplay")&&this.readyState!=4)$(this).one("play",function(){this.pause()});else this.pause&&!this.paused&&this.pause()})};
Asey.Utils.attachIframesAndObjectsToResumeMedia=function(a){var b=a.data("detached");if(b){for(var c=b.length-1;c>=0;c--){var d=b[c];!d.$next||d.$next.length==0?d.$parent.append(d.$node?d.$node:d.html):d.$next.before(d.$node?d.$node:d.html);d.$next=d.$parent=d.$node=d.html=void 0}a.data("detached",null)}$("video",a).each(function(){if(this.play&&this.getAttribute("autoplay")&&this.paused)this.currentTime=0,this.play()})};
(function(a){a(window);var b=a("html"),c=["src"],d=["hidpi-src","src"],f=a(".hidpi_button"),g=function(){this._mode="standard"};g.swapSources=function(a,b,c){var d=a.data(b);d&&!("src"==b&&a.hasClass("ImageInclude")&&"images/blank.gif"==a.attr("src")&&a.parents(".SlideShowWidget").length)&&("src"==c&&!a.data(c)&&a.data(c,a.attr("src")),a.attr("src",d))};g.isRetina=function(){if(1.5<=window.devicePixelRatio)return!0;if(window.matchMedia&&window.matchMedia("(-webkit-min-device-pixel-ratio: 1.5),(min--moz-device-pixel-ratio: 1.5),(-o-min-device-pixel-ratio: 3/2),(min-resolution: 1.5dppx)").matches)return!0;
return!1}();g.shouldUseCookie=0<f.length;g.getResolutionPreference=function(){return Asey.Utils.readCookie("aseyresolution")};g.saveResolutionPreference=function(a){Asey.Utils.createCookie("aseyresolution",a)};g.prototype.initializeHiDPIButton=function(){if(g.isRetina){var a=this;f.removeClass("unavailable").click(function(){switch(a._mode){case "standard":a.hidpiMode();break;case "hidpi":a.standardMode();break;default:Asey.Assert.assert(!1,"Unknown mode: "+a._mode)}})}};g.prototype.activate=function(){this.initializeHiDPIButton();
g.isRetina&&(!g.shouldUseCookie||"hidpi"==g.getResolutionPreference())?this.hidpiMode():this.standardMode()};g.prototype.getCurrentMode=function(){return this._mode};g.prototype.setCurrentMode=function(a){this._mode=a;if(g.isRetina){switch(a){case "standard":f.removeClass("on").addClass("off");break;case "hidpi":f.removeClass("off").addClass("on");break;default:Asey.Assert.assert(!1,"Unknown mode: "+a)}g.shouldUseCookie&&g.saveResolutionPreference(a)}};g.prototype.standardMode=function(){this.setCurrentMode("standard");
b.removeClass("hidpi");a("img").each(function(){g.swapSources(a(this),"src","hidpi-src")})};g.prototype.hidpiMode=function(){this.setCurrentMode("hidpi");b.addClass("hidpi");a("img").each(function(){g.swapSources(a(this),"hidpi-src","src")})};g.prototype.getDataSrcAttrName=function(){return"standard"==this._mode?c:d};a(window).data("ResolutionManager",new g)})(jQuery);Asey.Utils.detectScreenResolution=function(){$(window).data("ResolutionManager").activate()};
Asey.Utils.createCookie=function(a,b,c){if(c){var d=new Date;d.setTime(d.getTime()+c*864E5);c="; expires="+d.toGMTString()}else c="";document.cookie=a+"="+b+c+"; path=/"};Asey.Utils.readCookie=function(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];d.charAt(0)==" ";)d=d.substring(1,d.length);if(d.indexOf(a)==0)return d.substring(a.length,d.length)}return null};Asey.Utils.eraseCookie=function(a){createCookie(a,"",-1)};Asey.Browser={};
Asey.Browser.domPrefixes=["Webkit","Moz","O","ms","Khtml"];Asey.Browser.Features={};
Asey.Browser.Features.Touch=function(){if(navigator.maxTouchPoints>0)return{Start:"pointerDown",End:"pointerUp",Move:"pointerMove",Listener:function(a){return function(b){var c=b.originalEvent||b;if(c.pointerType!=c.POINTER_TYPE_MOUSE)return a.apply(this,arguments)}}};else for(var a=0,b=Asey.Browser.domPrefixes.length;a<b;a++){var c=Asey.Browser.domPrefixes[a];if(c+"MaxTouchPoints"in navigator&&navigator[c+"MaxTouchPoints"])return c=c.toUpperCase(),{Start:c+"PointerDown",End:c+"PointerUp",Move:c+
"PointerMove",Listener:function(a){return function(b){var d=b.originalEvent||b;if(d.pointerType!=d[c+"POINTER_TYPE_MOUSE"])return a.apply(this,arguments)}}}}try{return document.createEvent("TouchEvent"),{Start:"touchstart",End:"touchend",Move:"touchmove",Listener:function(a){return a}}}catch(d){}return!1}();
Asey.Browser.Features.checkCSSFeature=function(a,b){var c=Asey.Utils.toCamelCase(a),b=b||document.createElement("div");if(c in b.style)return!0;for(var c=c.charAt(0).toUpperCase()+c.substr(1),d=0,f=Asey.Browser.domPrefixes.length;d<f;d++)if(Asey.Browser.domPrefixes[d]+c in b.style)return Asey.Browser.domPrefixes[d];return!1};
Asey.Browser.Features.checkCSSValueCompatibility=function(a,b){var c=document.createElement("div"),a=Asey.Utils.toCamelCase(a),d=Asey.Browser.Features.checkCSSFeature(a,c);if(d)d!==!0&&(a=d+a.charAt(0).toUpperCase()+a.substr(1));else return!1;d=c.style[a];c.style[a]=b;if(c.style[a]!==d||b===d)return!0;for(var f=0;f<Asey.Browser.domPrefixes.length;f++){var g="-"+Asey.Browser.domPrefixes[f].toLowerCase()+"-"+b;c.style[a]=g;if(c.style[a]!==d)return Asey.Browser.domPrefixes[f]}return!1};
Asey.Browser.Bugs={};
Asey.Browser.Bugs.ClearNeedsOuterWidth=function(){var a=document.createElement("div");a.id="mbbcnow00";a.innerHTML='<div>a</div><style type="text/css">#mbbcnow00{position:absolute;top:-9999px;left:-9999px;visibility:hidden;} #mbbcnow01{width:1px;margin-right:-9999px;float:left} #mbbcnow02{clear:left;}</style>';var b=document.createElement("div"),c=document.createElement("div");document.body.appendChild(a);a.appendChild(b);a.appendChild(c);b.innerHTML="a";b.id="mbbcnow01";c.innerHTML="b";c.id="mbbcnow02";
b=c.getBoundingClientRect().top-b.getBoundingClientRect().top;document.body.removeChild(a);return b<1}();Asey.Browser.Bugs.CannotHandleClearBoth=function(){return jQuery.browser.msie&&7==jQuery.browser.version}();
Asey.Browser.Bugs.ScrollWidthHeightIncludesBorder=function(){var a=!1,b=$("<div>").css({border:"1px solid #000000;",width:100,height:100,position:"absolute",top:-99999,left:-99999,padding:0,margin:0,overflow:"auto"}).appendTo(document.body)[0];b.scrollHeight!==b.clientHeight&&(a=!0);$(b).remove();return a}();
(function(a){var b=a(window),c=a("body"),d=function(){this.pendingRequest=void 0;this.enabled=!0};d.prototype.init=function(d){this.$spacer=a(d+" .verticalspacer");this.$page=a(d);this.spacerMinHeight=1;this.$spacer.css("min-height",this.spacerMinHeight);this.$spacer.height()<this.spacerMinHeight&&this.$spacer.height(Math.floor(this.spacerMinHeight+1));this.spacerHeight=this.$spacer.height();this.pageMarginTop=Asey.Utils.getCSSIntValue(c,"padding-top")+Asey.Utils.getCSSIntValue(c,"margin-top");this.pageMarginBottom=
Asey.Utils.getCSSIntValue(c,"padding-bottom")+Asey.Utils.getCSSIntValue(c,"margin-bottom");this.pageResizeWatchEnabled=!0;this.alwaysVertScroll=c.hasClass("always_vert_scroll");this.updateSpacerMargin=0!=Asey.Utils.getCSSIntValue(this.$spacer,"margin-bottom");var g=this;if(Asey.Browser.Bugs.CannotHandleClearBoth&&0!=Asey.Utils.getCSSIntValue(this.$spacer,"margin-bottom"))this.$spacer.css("margin-bottom",0),this.updateSpacerMargin=!1;this.calculateInitialSpacerHeight();this.$page.watch("height",function(){g.onPageHeightChanged()});
b.resize(function(){g.doUpdate()});this.initialized=!0;this.doUpdate(this.pendingRequest)};d.prototype.updateScrollClass=function(a){var a=this.spacerMinHeight<Math.floor(a*100)/100,b=!1;this.alwaysVertScroll||(a&&!c.hasClass("no_vert_scroll")?(c.addClass("no_vert_scroll"),b=!0):!a&&c.hasClass("no_vert_scroll")&&(c.removeClass("no_vert_scroll"),b=!0));b&&this.$spacer.css("height")};d.prototype.doUpdate=function(a){if(this.enabled)if(this.initialized){parseInt(a)||(a=0);this.updateSpacerMargin&&this.$spacer.css("margin-bottom",
-(this.$spacer.offset().top-this.pageMarginTop));var c=this.$page.outerHeight(!0),d=c-this.spacerHeight,a=Math.max(this.spacerMinHeight,b.height()-this.pageMarginTop-this.pageMarginBottom-d-a);if(a!=this.spacerHeight){this.pageResizeWatchEnabled=!1;this.updateScrollClass(a);this.$spacer.css("height",a);if(a<this.spacerHeight&&c==this.$page.outerHeight(!0))a=this.spacerHeight,this.updateScrollClass(a),this.$spacer.css("height",a);this.pageResizeWatchEnabled=!0}return this.spacerHeight=a}else this.pendingRequest=
a};d.prototype.calculateInitialSpacerHeight=function(){for(var a=0,b=0;b++<20;){var c=this.doUpdate();if(c<=a)break;a=c}};d.prototype.onPageHeightChanged=function(a){this.pageResizeWatchEnabled&&this.doUpdate(a)};d.prototype.enable=function(){this.enabled=!0};d.prototype.disable=function(){this.enabled=!1};b.data("stickyFooter",new d("#page"))})(jQuery);
Asey.Utils.requestAnimationFrame=function(){return window.webkitRequestAnimationFrame&&window.webkitRequestAnimationFrame.bind(window)||window.mozRequestAnimationFrame&&window.mozRequestAnimationFrame.bind(window)||window.requestAnimationFrame&&window.requestAnimationFrame.bind(window)||function(a){window.setTimeout(a,20)}}();
Asey.Utils.animationFrameFx=function(a,b){var c=a.fx;a.extend(c,a.fx);var d,f=a(b).data("stickyFooter"),g=function(){d&&(Asey.Utils.requestAnimationFrame(g),c.tick(),f.doUpdate())};c.timer=function(b){b()&&a.timers.push(b)&&!d&&(d=!0,g())};c.stop=function(){d=!1};a.fn.animationFrameFx=c}(jQuery,this);
;(function(){if(!("undefined"==typeof Asey||"undefined"==typeof Asey.assets)){var a=function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]==b)return c;return-1}(Asey.assets.required,"aseyutils.js");if(-1!=a){Asey.assets.required.splice(a,1);for(var a=document.getElementsByTagName("meta"),b=0,c=a.length;b<c;b++){var d=a[b];if("generator"==d.getAttribute("name")){"2014.2.1.284"!=d.getAttribute("content")&&Asey.assets.outOfDate.push("aseyutils.js");break}}}}})();
